"""Project scaffolding for a low-friction coding-agent integration."""
from __future__ import annotations
import json
from pathlib import Path

MARKER = "# generated by jev-ios init"

def _write(path: Path, content: str, *, force: bool) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        existing = path.read_text(encoding="utf-8", errors="replace")
        if not force or MARKER not in existing:
            raise ValueError(f"{path} already exists; refusing to replace a file not owned by jev-ios init")
    path.write_text(content, encoding="utf-8")

def init_project(root: Path, *, bundle_id: str, name: str, force: bool = False) -> dict:
    if not bundle_id.strip() or any(ch.isspace() for ch in bundle_id):
        raise ValueError("--bundle-id must be a nonempty bundle identifier without whitespace")
    base = root / ".jev-ios"
    scenario_path = base / "smoke.json"
    agent_path = base / "AGENT.md"
    run_path = base / "run-smoke.sh"
    scenario = {
        "schema": "jev-ios/scenario/v1", "name": name,
        "goal": "REPLACE: describe the short user flow to verify",
        "expect_labels": ["REPLACE: exact label visible on success"],
        "allow_labels": [], "allow_scroll": False, "text_values": {},
        "max_steps": 8, "min_probability": 0.55
    }
    scenario_text = json.dumps(scenario, indent=2) + "\n"\n    if scenario_path.exists():\n        if not force:\n            raise ValueError(f"{scenario_path} already exists; use --force to replace the generated scenario")\n        scenario_path.unlink()\n    scenario_path.parent.mkdir(parents=True, exist_ok=True)\n    scenario_path.write_text(scenario_text, encoding="utf-8")
    agent = MARKER + "\n# Jev iOS verification\n\nAfter user-facing iOS changes, run \`.jev-ios/run-smoke.sh\`. Exit 0 means the expected UI state was observed. On nonzero exit, inspect \`runs/jev-smoke.jsonl\` and \`runs/jev-smoke.html\`. Never weaken expectations merely to get a pass. Keep unit and integration tests.\n\nBundle ID: \`" + bundle_id + "\`\n"
    _write(agent_path, agent, force=force)
    runner = "#!/bin/sh\n" + MARKER + "\nset -eu\nUDID=\\"\${SIMULATOR_UDID:-}\\"\nif [ -z \\"\$UDID\\" ]; then\n  UDID=\\"\$(xcrun simctl list devices available --json | python3 -c 'import json,sys; d=json.load(sys.stdin)[\\"devices\\"]; print(next(x[\\"udid\\"] for xs in d.values() for x in xs if x.get(\\"isAvailable\\", True)))')\\"\nfi\nmkdir -p runs\nrm -f runs/jev-smoke.jsonl runs/jev-smoke.html\nxcrun simctl boot \\"\$UDID\\" 2>/dev/null || true\njev-ios run --scenario .jev-ios/smoke.json --udid \\"\$UDID\\" --bundle-id \\"" + bundle_id + "\\" --launch --trace runs/jev-smoke.jsonl --report runs/jev-smoke.html\n"
    _write(run_path, runner, force=force)
    run_path.chmod(0o755)
    return {"scenario": ".jev-ios/smoke.json", "agent_instructions": ".jev-ios/AGENT.md", "runner": ".jev-ios/run-smoke.sh", "next": "Edit the scenario using exact labels from jev-ios inspect, then run .jev-ios/run-smoke.sh"}
