"""Non-destructive project scaffolding; no model calls or device actions."""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

from .matrix_report import write_json, write_text
from .suite import bundle_identifier, read_json, text

MARKER = "# generated by jev-ios init"
SKILL_URL = "https://github.com/Clueless-Creations/jev-ios-ultrafast/blob/main/SKILL.md"


def init_project(root: Path, *, bundle_id: str, name: str, force: bool = False) -> dict:
    from .lease import Lease
    with Lease("project-init:" + str(root.resolve())):
        return _init_project(root, bundle_id=bundle_id, name=name, force=force)


def _init_project(root: Path, *, bundle_id: str, name: str, force: bool = False) -> dict:
    bundle_identifier(bundle_id)
    text(name, "scenario name")
    base = root / ".jev-ios"
    if base.is_symlink():
        raise ValueError("Refusing a symlinked .jev-ios directory")
    scenario = {"schema": "jev-ios/scenario/v1", "name": name,
                "goal": "REPLACE: describe the short user flow to verify",
                "expect_labels": ["REPLACE: exact label visible on success"],
                "allow_labels": [], "allow_scroll": False, "text_values": {},
                "max_steps": 8, "min_probability": 0.55}
    suite = {"schema": "jev-ios/suite/v1", "name": name, "bundle_id": bundle_id,
             "fixture_isolation": "shared", "start_labels": ["REPLACE: exact label at the prepared start"],
             "launch_args": [], "cases": [{"id": "smoke", "scenario": "smoke.json", "critical": True,
                                            "paths": [], "tags": ["smoke"]}]}
    installed_skill = Path(__file__).resolve().parent.parent / "SKILL.md"
    skill = (installed_skill.read_text(encoding="utf-8") if installed_skill.is_file() else
             "# Jev iOS\n\nRead " + SKILL_URL + " before mapping scenarios or operating a test app.\n")
    instructions = f"""# generated by jev-ios init
# Jev verification for {bundle_id}

Read `.jev-ios/SKILL.md` before operating the app or changing Jev files.

For user-facing work:
1. Follow this repo's existing build/install workflow. Do not invent one for Jev.
2. Inspect the authorized installed app before writing or changing scenario labels.
3. Use bounded Jev learning only when unfamiliar navigation makes it useful.
4. Encode the requested user outcome in the smallest focused scenario.
5. Run the relevant suite after the change.
6. Read the summary first; open only relevant failing evidence.
7. Do not weaken assertions merely to make a run pass.

If MobAI is configured, prefer it for multiple, physical, remote, or cloud
devices. Run `jev-ios mobai-devices` and create a pool with
`transport: "mobai"`. For the smallest local iOS setup, native AXe + simctl is
fine. XcodeBuildMCP is not required.

Run `.jev-ios/run-smoke.sh` for the starter local smoke flow. For a pool:

`jev-ios plan --suite .jev-ios/suite.json --pool <pool.json> --changed-since main`
`jev-ios matrix --suite .jev-ios/suite.json --pool <pool.json> --changed-since main --mode shard`

Keep `fixture_isolation: shared` until devices have independent fixture data.
A verified Jev result is semantic UI evidence, not backend or visual acceptance.
Never replay an uncertain action blindly. Keep app maps, traces and reports out
of source control because observed UI may contain app data.

Add a pointer to this file from the app's existing AGENTS.md or CLAUDE.md. Init
deliberately does not overwrite those files.
"""
    runner = '''#!/bin/sh
# generated by jev-ios init
set -eu
ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
cd "$ROOT"
if [ -n "${SIMULATOR_UDID:-}" ]; then
  set -- --udid "$SIMULATOR_UDID" "$@"
else
  set -- --devices auto "$@"
fi
exec jev-ios matrix --suite .jev-ios/suite.json --mode shard --parallel 1 "$@"
'''
    contents = {"smoke.json": json.dumps(scenario, indent=2) + "\n",
                "suite.json": json.dumps(suite, indent=2) + "\n", "AGENT.md": instructions,
                "SKILL.md": skill, "run-smoke.sh": runner,
                ".gitignore": "app-map*.json\nruns/\n"}
    ownership = base / "generated.json"
    if ownership.is_symlink():
        raise ValueError("Refusing symlinked generation metadata")
    old = read_json(ownership) if ownership.exists() else {}
    # Validate every destination before writing anything. --force replaces only
    # byte-identical generated files, never a user-edited scenario or guide.
    for filename in contents:
        target = base / filename
        if target.is_symlink():
            raise ValueError("Refusing a symlinked generated file")
        if target.exists():
            expected = old.get("hashes", {}).get(filename)
            actual = hashlib.sha256(target.read_bytes()).hexdigest()
            if not force or expected != actual:
                raise ValueError("Existing or edited project files are preserved; choose a fresh directory or reconcile them manually")
    if ownership.is_symlink() or (ownership.exists() and not force):
        raise ValueError("Existing generation metadata is preserved")
    base.mkdir(parents=True, exist_ok=True)
    backups = {n: (base / n).read_bytes() if (base / n).exists() else None for n in [*contents, "generated.json"]}
    try:
        for filename, value in contents.items():
            write_text(base / filename, value)
        (base / "run-smoke.sh").chmod(0o755)
        write_json(ownership, {"schema": "jev-ios/generated/v1", "hashes": {
            n: hashlib.sha256(v.encode()).hexdigest() for n, v in contents.items()}})
    except BaseException:
        for filename, previous in backups.items():
            if previous is None:
                (base / filename).unlink(missing_ok=True)
            else:
                (base / filename).write_bytes(previous)
        raise
    return {"scenario": ".jev-ios/smoke.json", "suite": ".jev-ios/suite.json",
            "agent_instructions": ".jev-ios/AGENT.md", "skill": ".jev-ios/SKILL.md", "runner": ".jev-ios/run-smoke.sh",
            "next": "Inspect the test app, replace the scenario and start-label placeholders, then run the wrapper. Add /runs/ to the app's .gitignore."}
